// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using internetiot.Data;

namespace internetiot.Migrations
{
    [DbContext(typeof(RageRoomsContext))]
    [Migration("20180828131457_Create_RageRoomDb")]
    partial class Create_RageRoomDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("internetiot.Models.RageRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Description");

                    b.Property<int>("Duration");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longtitude");

                    b.Property<int>("MaxParticipants");

                    b.Property<int>("MinParticipants");

                    b.Property<string>("Name");

                    b.Property<int>("PricePerParticipant");

                    b.HasKey("Id");

                    b.ToTable("RageRooms");
                });

            modelBuilder.Entity("internetiot.Models.Rate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment");

                    b.Property<int?>("RageRoomId");

                    b.Property<int>("Score");

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("Id");

                    b.HasIndex("RageRoomId");

                    b.ToTable("Rates");
                });

            modelBuilder.Entity("internetiot.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("RageRoomId");

                    b.Property<int>("Participants");

                    b.Property<DateTime>("StartingTime");

                    b.Property<float>("TotalPrice");

                    b.HasKey("Id");

                    b.HasIndex("RageRoomId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("internetiot.Models.Rate", b =>
                {
                    b.HasOne("internetiot.Models.RageRoom", "RageRoom")
                        .WithMany("Rates")
                        .HasForeignKey("RageRoomId");
                });

            modelBuilder.Entity("internetiot.Models.Reservation", b =>
                {
                    b.HasOne("internetiot.Models.RageRoom", "RageRoom")
                        .WithMany()
                        .HasForeignKey("RageRoomId");
                });
#pragma warning restore 612, 618
        }
    }
}
